s = "AUGGCCAUGGCGCCCAGAACUGAGAUCAAUAGUACCCGUAUUAACGGGUGA"
l = list(s)
st = 3
ll = [l[i:i+st] for i in range(0, len(l), st)]
nl = []
for i in ll:
    ns = ''.join(i)
    ns = ns.upper()
    nl.append(ns)
rel = [ "F" if j == "UUU"
        else "F" if j == "UUC"
        else "L" if j == "UUA"
        else "L" if j == "UUG"
        else "L" if j == "CUU"
        else "L" if j == "CUC"
        else "L" if j == "CUA"
        else "L" if j == "CUG"
        else "I" if j == "AUU"
        else "I" if j == "AUC"
        else "I" if j == "AUA"
        else "\033[1;31;mM\033[0m" if j == "AUG"
        else "V" if j == "GUU"
        else "V" if j == "GUC"
        else "V" if j == "GUA"
        else "V" if j == "GUG"
        else "S" if j == "UCU"
        else "S" if j == "UCC"
        else "S" if j == "UCA"
        else "S" if j == "UCG"
        else "P" if j == "CCU"
        else "P" if j == "CCC"
        else "P" if j == "CCA"
        else "P" if j == "CCG"
        else "T" if j == "ACU"
        else "T" if j == "ACC"
        else "T" if j == "ACA"
        else "T" if j == "ACG"
        else "A" if j == "GCU"
        else "A" if j == "GCC"
        else "A" if j == "GCG"
        else "A" if j == "GCA"
        else "Y" if j == "UAU"
        else "Y" if j == "UAC"
        else "\033[1;37;40m*\033[0m" if j == "UAG"
        else "\033[1;37;40m*\033[0m" if j == "UAA"
        else "H" if j == "CAU"
        else "H" if j == "CAC"
        else "Q" if j == "CAA"
        else "Q" if j == "CAG"
        else "N" if j == "AAU"
        else "N" if j == "AAC"
        else "K" if j == "AAA"
        else "K" if j == "AAG"
        else "D" if j == "GAU"
        else "D" if j == "GAC"
        else "E" if j == "GAA"
        else "E" if j == "GAG"
        else "C" if j == "UGU"
        else "C" if j == "UGC"
        else "\033[1;37;40m*\033[0m" if j == "UGA"
        else "W" if j == "UGG"
        else "R" if j == "CGU"
        else "R" if j == "CGC"
        else "R" if j == "CGA"
        else "R" if j == "CGG"
        else "S" if j == "AGU"
        else "S" if j == "AGC"
        else "R" if j == "AGA"
        else "R" if j == "AGG"
        else "G" if j == "GGU"
        else "G" if j == "GGC"
        else "G" if j == "GGA"
        else "G" if j == "GGG"
        else "X" for j in nl]
re = ''.join(rel)
print(re)